### ISSUE TITLE
Merging files and cloud upload

### ISSUE THREAD

**Issue by sadovnychyi** [nicolashahn/pi-helmet-cam#1]
Hi!

Thanks for this project, I decided to build one for myself after finding this.

I made some improvements in which you could be interested:
* Magnetic cable makes a huge difference in connecting power to your raspberry (kind of magsafe)
* You can simply append one video chunk into another one – this way you don't need to create a new file every 5 seconds. Still failsafe. I added some logic to split them once they are too big, but mostly you will get a single video file for a single trip.
* Added automatic youtube [uploading](https://github.com/sadovnychyi/pi-helmet-cam/blob/2384654f143f59c2d9aa8627679d06a233997813/camera.py#L143-L171) – recording stops when you are near wifi and uploading starts

My first try is to mount it on *inside* of my helmet, so far looks good:
![img_20171219_010251](https://user-images.githubusercontent.com/193864/34120191-c344ca82-e45f-11e7-80aa-55c0eeb463d1.jpg)

https://github.com/sadovnychyi/pi-helmet-cam

**Comment by nicolashahn** [comment]
Hey Dmytro,

Thanks for the email, I’m glad my work is useful to someone else! 

- With a magnetic cable, are you not worried it might come out too easily? I figure a normal cable would be more likely to stay connected in case of an accident.
- I’ll take a look at your code and probably add the video chunking to mine - I was hoping for a way to do that, thanks for finding it for me.
- Very cool. I definitely need to smooth out the pipeline from recording -> publishing, good work!
- Your mount is super low profile - does the visor affect the video quality? Especially if you use a tinted one like I do. If it still works well I’ll make a similar change.

Overall looks great, fantastic additions.

Nick
